#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
 
use UNIVERSAL::require;
use File::Basename 'dirname';
use File::Spec::Functions qw(catdir splitdir);
 
# Source directory has precedence
my @base = (splitdir(dirname(__FILE__)), '..');
my $lib = join('/', @base, 'lib');
-e catdir(@base, 't') ? unshift(@INC, $lib) : push(@INC, $lib);
 
my $cmd = shift @ARGV;
my $module = "SaisokuAuction::Cli::$cmd";
$module->require;
$module->run( @ARGV );